// business action types
export const GET_BUSINESSES_START = 'GET_BUSINESSES_START';
export const GET_BUSINESSES_SUCCESS = 'GET_BUSINESSES_SUCCESS';
export const GET_BUSINESSES_FAILURE = 'GET_BUSINESSES_FAILURE';

// favorite action types
export const ADD_BUSINESS_TO_FAVORITES = 'ADD_BUSINESS_TO_FAVORITES';
export const REMOVE_BUSINESS_FROM_FAVORITES = 'REMOVE_BUSINESS_FROM_FAVORITES';
